#!/usr/bin/env bash
# One entry point for the local SearXNG container. Everything it touches lives in
# this folder or in Docker: no host packages, no state written into the repo.
#
#   ./searxng.sh up        start it (generates .env with a per-machine secret)
#   ./searxng.sh status    health, engine counts, and a live query
#   ./searxng.sh verify    websearch doctor --check searxng, plus the container's egress IP
#   ./searxng.sh egress    where SearXNG's engine requests leave from
#   ./searxng.sh engines   re-probe every engine and regenerate settings.yml
#   ./searxng.sh restart   apply a settings.yml change
#   ./searxng.sh logs      follow container logs
#   ./searxng.sh down      stop and remove (add --purge to drop the cache volume)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE=(docker compose -f "$HERE/docker-compose.yml")
ENV_FILE="$HERE/.env"

port() {
  # .env wins, then the environment, then the compose default.
  local from_env
  from_env="$(grep -E '^SEARXNG_PORT=' "$ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2- || true)"
  echo "${from_env:-${SEARXNG_PORT:-8888}}"
}

url() { echo "http://127.0.0.1:$(port)"; }

need_docker() {
  command -v docker >/dev/null || { echo "docker is not installed" >&2; exit 1; }
  docker compose version >/dev/null 2>&1 || { echo "the docker compose plugin is missing" >&2; exit 1; }
}

ensure_env() {
  if [ -f "$ENV_FILE" ] && grep -q '^SEARXNG_SECRET=' "$ENV_FILE"; then
    return
  fi
  local secret
  secret="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  {
    echo "# Generated by searxng.sh. Machine-local, gitignored, safe to delete."
    echo "SEARXNG_SECRET=$secret"
    echo "SEARXNG_PORT=${SEARXNG_PORT:-8888}"
  } >>"$ENV_FILE"
  echo "wrote $ENV_FILE with a fresh secret"
}

egress_proxy() {
  # What SearXNG itself should route its engine requests through. The client's own hop
  # to a loopback SearXNG is never proxied (it cannot be), so this is the only place
  # the searches get anonymized.
  #
  #   SEARXNG_OUTGOING_PROXY   explicit URL, or "off" to force direct egress
  #   WEBSEARCH_PROXY          otherwise reuse the tool's proxy, expanded by the same
  #                            resolver the CLI uses so "nordvpn" shorthand works
  local explicit="${SEARXNG_OUTGOING_PROXY:-}"
  if [ -z "$explicit" ] && [ -f "$ENV_FILE" ]; then
    explicit="$(grep -E '^SEARXNG_OUTGOING_PROXY=' "$ENV_FILE" | tail -1 | cut -d= -f2- || true)"
  fi
  case "$(printf '%s' "$explicit" | tr '[:upper:]' '[:lower:]')" in
    off | none | direct) return 0 ;;
    "") ;;
    *) echo "$explicit"; return 0 ;;
  esac

  [ -n "${WEBSEARCH_PROXY:-}" ] || return 0
  if ! command -v uv >/dev/null; then
    echo "WEBSEARCH_PROXY is set but uv is missing, so it cannot be expanded;" >&2
    echo "set SEARXNG_OUTGOING_PROXY to the proxy URL to route SearXNG's egress." >&2
    return 0
  fi
  ( cd "$HERE/../.." && uv run --quiet python -c \
      'from websearch.proxy import resolve_proxy; print(resolve_proxy() or "")' 2>/dev/null )
}

render_settings() {
  local proxy
  proxy="$(egress_proxy)"
  python3 "$HERE/tools/render-settings.py" --proxy "$proxy"
}

wait_ready() {
  local base="$1" i
  for i in $(seq 1 60); do
    if curl -fsS -o /dev/null "$base/healthz" 2>/dev/null; then
      echo "ready at $base (${i}s)"
      return 0
    fi
    sleep 1
  done
  echo "SearXNG did not come up within 60s; check: $0 logs" >&2
  return 1
}

cmd_up() {
  need_docker
  ensure_env
  render_settings
  "${COMPOSE[@]}" up -d
  wait_ready "$(url)"
  echo
  echo "point the tool at it:"
  echo "  export WEBSEARCH_SEARXNG_URL=$(url)"
}

cmd_down() {
  need_docker
  if [ "${1:-}" = "--purge" ]; then
    "${COMPOSE[@]}" down --volumes
    echo "removed the container and its cache volume"
  else
    "${COMPOSE[@]}" down
  fi
}

cmd_restart() {
  need_docker
  render_settings
  "${COMPOSE[@]}" up -d --force-recreate
  wait_ready "$(url)"
}

cmd_status() {
  need_docker
  local base
  base="$(url)"
  "${COMPOSE[@]}" ps
  echo
  if ! curl -fsS -o /dev/null "$base/healthz" 2>/dev/null; then
    echo "not responding at $base - start it with: $0 up"
    return 1
  fi
  curl -fsS "$base/config" | python3 -c '
import json, sys, collections
config = json.load(sys.stdin)
engines = config["engines"]
active = [e for e in engines if e.get("enabled")]
print("SearXNG " + str(config.get("version")))
print("engines: {} active / {} available".format(len(active), len(engines)))
cats = collections.Counter(c for e in active for c in e["categories"])
print("active by category: " + ", ".join("{}={}".format(k, v) for k, v in cats.most_common(6)))
'
  echo
  echo "live query (general):"
  curl -fsS "$base/search?q=rust+ownership&format=json" | python3 -c '
import json, sys
payload = json.load(sys.stdin)
results = payload["results"]
answered = sorted({e for r in results for e in r.get("engines", [])})
print("  {} results from {} engines".format(len(results), len(answered)))
print("  " + ", ".join(answered))
silent = payload.get("unresponsive_engines") or []
if silent:
    print("  {} engines did not answer (SearXNG suspends those on its own)".format(len(silent)))
'
}

cmd_verify() {
  # The health, engine-count, and live-query checks live in `websearch doctor`, which
  # every install has; this adds the one thing the doctor cannot see from outside the
  # container, which is where SearXNG's own engine requests leave from.
  need_docker
  ( cd "$HERE/../.." && uv run websearch doctor --check searxng --searxng-url "$(url)" ) || exit 1
  echo
  cmd_egress
}

cmd_egress() {
  # Where SearXNG's engine requests actually come from. Prints IPs only, never the
  # proxy URL: that carries credentials.
  need_docker
  echo "egress:"
  echo "  host, direct:      $(curl -fsS --max-time 20 https://api.ipify.org || echo unreachable)"
  docker exec websearch-searxng /usr/local/searxng/.venv/bin/python -c '
import asyncio, yaml, httpx

config = yaml.safe_load(open("/etc/searxng/settings.yml"))
proxies = (config.get("outgoing") or {}).get("proxies")
if not proxies:
    print("  searxng container: direct (no outgoing proxy configured)")
    raise SystemExit(0)
url = list(proxies.values())[0] if isinstance(proxies, dict) else proxies
if isinstance(url, list):
    url = url[0]

from searx.network.client import get_transport_for_socks_proxy

async def main():
    if url.startswith("socks"):
        transport = get_transport_for_socks_proxy(True, False, "", url, httpx.Limits(), 0)
        client = httpx.AsyncClient(transport=transport)
    else:
        client = httpx.AsyncClient(proxy=url)
    async with client:
        r = await client.get("https://api.ipify.org", timeout=30)
        print("  searxng container: " + r.text + " (through the configured proxy)")

asyncio.run(main())
' 2>/dev/null || echo "  searxng container: could not determine (is it running?)"
}

cmd_engines() {
  need_docker
  python3 "$HERE/tools/probe-engines.py" --url "$(url)" "$@"
}

case "${1:-}" in
  up) shift; cmd_up "$@" ;;
  egress) shift; cmd_egress "$@" ;;
  down) shift; cmd_down "$@" ;;
  restart) shift; cmd_restart "$@" ;;
  status) shift; cmd_status "$@" ;;
  verify) shift; cmd_verify "$@" ;;
  engines) shift; cmd_engines "$@" ;;
  logs) shift; need_docker; "${COMPOSE[@]}" logs -f "$@" ;;
  *)
    # The header comment is the usage text; print it up to the first line of code.
    awk 'NR>1 { if ($0 !~ /^#/) exit; sub(/^# ?/, ""); print }' "${BASH_SOURCE[0]}"
    exit 1
    ;;
esac
