#!/usr/bin/env bash
# One entry point for the local SearXNG container. Everything it touches lives in
# this folder or in Docker: no host packages, no state written into the repo.
#
#   ./searxng.sh up        start it (generates .env with a per-machine secret)
#   ./searxng.sh status    health, engine counts, and a live query
#   ./searxng.sh verify    end-to-end check through the websearch CLI
#   ./searxng.sh engines    re-probe every engine and regenerate settings.yml
#   ./searxng.sh restart   apply a settings.yml change
#   ./searxng.sh logs      follow container logs
#   ./searxng.sh down      stop and remove (add --purge to drop the cache volume)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE=(docker compose -f "$HERE/docker-compose.yml")
ENV_FILE="$HERE/.env"

port() {
  # .env wins, then the environment, then the compose default.
  local from_env
  from_env="$(grep -E '^SEARXNG_PORT=' "$ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2- || true)"
  echo "${from_env:-${SEARXNG_PORT:-8888}}"
}

url() { echo "http://127.0.0.1:$(port)"; }

need_docker() {
  command -v docker >/dev/null || { echo "docker is not installed" >&2; exit 1; }
  docker compose version >/dev/null 2>&1 || { echo "the docker compose plugin is missing" >&2; exit 1; }
}

ensure_env() {
  if [ -f "$ENV_FILE" ] && grep -q '^SEARXNG_SECRET=' "$ENV_FILE"; then
    return
  fi
  local secret
  secret="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  {
    echo "# Generated by searxng.sh. Machine-local, gitignored, safe to delete."
    echo "SEARXNG_SECRET=$secret"
    echo "SEARXNG_PORT=${SEARXNG_PORT:-8888}"
  } >>"$ENV_FILE"
  echo "wrote $ENV_FILE with a fresh secret"
}

wait_ready() {
  local base="$1" i
  for i in $(seq 1 60); do
    if curl -fsS -o /dev/null "$base/healthz" 2>/dev/null; then
      echo "ready at $base (${i}s)"
      return 0
    fi
    sleep 1
  done
  echo "SearXNG did not come up within 60s; check: $0 logs" >&2
  return 1
}

cmd_up() {
  need_docker
  ensure_env
  "${COMPOSE[@]}" up -d
  wait_ready "$(url)"
  echo
  echo "point the tool at it:"
  echo "  export WEBSEARCH_SEARXNG_URL=$(url)"
}

cmd_down() {
  need_docker
  if [ "${1:-}" = "--purge" ]; then
    "${COMPOSE[@]}" down --volumes
    echo "removed the container and its cache volume"
  else
    "${COMPOSE[@]}" down
  fi
}

cmd_restart() {
  need_docker
  "${COMPOSE[@]}" up -d --force-recreate
  wait_ready "$(url)"
}

cmd_status() {
  need_docker
  local base
  base="$(url)"
  "${COMPOSE[@]}" ps
  echo
  if ! curl -fsS -o /dev/null "$base/healthz" 2>/dev/null; then
    echo "not responding at $base - start it with: $0 up"
    return 1
  fi
  curl -fsS "$base/config" | python3 -c '
import json, sys, collections
config = json.load(sys.stdin)
engines = config["engines"]
active = [e for e in engines if e.get("enabled")]
print("SearXNG " + str(config.get("version")))
print("engines: {} active / {} available".format(len(active), len(engines)))
cats = collections.Counter(c for e in active for c in e["categories"])
print("active by category: " + ", ".join("{}={}".format(k, v) for k, v in cats.most_common(6)))
'
  echo
  echo "live query (general):"
  curl -fsS "$base/search?q=rust+ownership&format=json" | python3 -c '
import json, sys
payload = json.load(sys.stdin)
results = payload["results"]
answered = sorted({e for r in results for e in r.get("engines", [])})
print("  {} results from {} engines".format(len(results), len(answered)))
print("  " + ", ".join(answered))
silent = payload.get("unresponsive_engines") or []
if silent:
    print("  {} engines did not answer (SearXNG suspends those on its own)".format(len(silent)))
'
}

cmd_verify() {
  need_docker
  local base
  base="$(url)"
  curl -fsS -o /dev/null "$base/healthz" || { echo "not running; start with: $0 up" >&2; exit 1; }
  echo "querying through the websearch CLI against $base"
  ( cd "$HERE/../.." && WEBSEARCH_SEARXNG_URL="$base" uv run websearch search "rust ownership" \
      --json --no-ddgs --count 10 ) | python3 -c '
import json, sys
envelope = json.load(sys.stdin)
if not envelope.get("ok"):
    print("  search failed: " + json.dumps(envelope.get("error")))
    sys.exit(1)
results = (envelope.get("data") or {}).get("results") or []
print("  backend={} results={}".format(envelope["meta"].get("backend"), len(results)))
for r in results[:3]:
    print("  - " + r["title"][:70])
    print("    " + r["url"][:90])
sys.exit(0 if results else 1)
'
  echo "searxng path works end to end"
}

cmd_engines() {
  need_docker
  python3 "$HERE/tools/probe-engines.py" --url "$(url)" "$@"
}

case "${1:-}" in
  up) shift; cmd_up "$@" ;;
  down) shift; cmd_down "$@" ;;
  restart) shift; cmd_restart "$@" ;;
  status) shift; cmd_status "$@" ;;
  verify) shift; cmd_verify "$@" ;;
  engines) shift; cmd_engines "$@" ;;
  logs) shift; need_docker; "${COMPOSE[@]}" logs -f "$@" ;;
  *)
    sed -n '2,12p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 1
    ;;
esac
