"""Run SearXNG on this machine without Docker.

``docker/searxng/`` is the deployment story for a host that has Docker. This module is
the one for a process that does not: an agent sandbox, a CI job, a laptop with no
daemon socket. It clones upstream SearXNG, builds a virtualenv beside it, writes a
settings file with the JSON API on, and starts the server detached from the caller.

Detached is the load-bearing word. Agent CLIs run each shell command as a process group
and kill the group when the command returns, so a plain ``server &`` dies the moment the
tool call ends. The child here gets its own session (``start_new_session=True``) and
writes to a log file instead of the inherited pipe, which is what lets it outlive the
command that started it.

Nothing is written outside the state directory, and the only network access is the git
clone plus the dependency download.
"""

from __future__ import annotations

import json
import os
import re
import secrets
import shutil
import signal
import subprocess
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from . import errors
from .envelope import Envelope, error_envelope, ok_envelope
from .optional_layers import SEARXNG_ENV, redact_url, write_env_setting
from .proxy import ProxyConfigError

SEARXNG_CONTRACT_VERSION = "1.2.0"

UPSTREAM = "https://github.com/searxng/searxng"

HOME_VAR = "WEBSEARCH_SEARXNG_HOME"
PORT_VAR = "WEBSEARCH_SEARXNG_PORT"
REF_VAR = "WEBSEARCH_SEARXNG_REF"
# Overrides what this instance's own engine requests leave through: a proxy URL, or an
# off word for direct egress. Unset means the tool's egress, which is the point of it.
OUTGOING_PROXY_VAR = "SEARXNG_OUTGOING_PROXY"

DEFAULT_PORT = 8888
HEALTH_TIMEOUT_S = 90
# Seconds added to every engine timeout while the instance goes through a proxy. A SOCKS
# exit costs a round trip that the engines' own timeouts were not sized for. An integer
# because SearXNG's settings schema types it as one and refuses to start on a float.
EXTRA_PROXY_TIMEOUT_S = 10

# The line that says this file is still the tool's to regenerate. Delete it (or edit the
# file however you like and remove it) and `up` will never touch the file again.
MANAGED_MARKER = "# websearch-managed: regenerated by `websearch searxng up`"

# use_default_settings keeps every engine, locale, and header default upstream ships and
# overrides only what a local API instance needs: a machine-local bind, the JSON format
# the search layer asks for, and the limiter off (it exists to slow down strangers, and
# there are none on loopback).
SETTINGS_TEMPLATE = """\
{marker}
# Remove the line above to take ownership of this file; it is rewritten on every `up`
# while that marker is present, because the egress below follows settings that change
# between runs.
use_default_settings: true
general:
  debug: false
  instance_name: "websearch-local"
server:
  bind_address: "127.0.0.1"
  port: {port}
  secret_key: "{secret}"
  limiter: false
  public_instance: false
  image_proxy: false
search:
  formats:
    - html
    - json
{outgoing}{engines}"""

# SearXNG's onion engines (ahmia, torch) are in the "onions" category and only work
# through Tor, and they get the Tor address per engine even when the instance already has
# an outgoing proxy: with a VPN proxy configured, that global entry is not a Tor port and
# an onion address would go nowhere. SearXNG verifies a using_tor_proxy engine against
# check.torproject.org before it will use it.
ONION_ENGINES_TEMPLATE = """\
engines:
  - name: ahmia
    using_tor_proxy: true
    proxies:
      all://:
        - {socks}
  - name: torch
    using_tor_proxy: true
    proxies:
      all://:
        - {socks}
"""


# What `up` wrote before the file became regenerable. An unedited copy of this is adopted
# rather than left behind: see ``_is_ours``.
LEGACY_SETTINGS_TEMPLATE = """\
# Generated by `websearch searxng up`. Safe to edit; `up` never overwrites it.
use_default_settings: true
general:
  debug: false
  instance_name: "websearch-local"
server:
  bind_address: "127.0.0.1"
  port: {port}
  secret_key: "{secret}"
  limiter: false
  public_instance: false
  image_proxy: false
search:
  formats:
    - html
    - json
"""


class SearxngError(RuntimeError):
    """A step of the local stack failed with something the caller can act on."""


@dataclass(frozen=True)
class Paths:
    home: Path

    def __post_init__(self) -> None:
        if not isinstance(self.home, Path):
            object.__setattr__(self, "home", Path(self.home))

    @property
    def src(self) -> Path:
        return self.home / "src"

    @property
    def venv(self) -> Path:
        return self.home / "venv"

    @property
    def python(self) -> Path:
        return self.venv / "bin" / "python"

    @property
    def granian(self) -> Path:
        return self.venv / "bin" / "granian"

    @property
    def settings(self) -> Path:
        return self.home / "settings.yml"

    @property
    def log(self) -> Path:
        return self.home / "searxng.log"

    @property
    def pidfile(self) -> Path:
        return self.home / "searxng.pid"


def home_dir() -> Path:
    """Where the checkout, the venv, and the runtime state live.

    An explicit ``WEBSEARCH_SEARXNG_HOME`` wins; otherwise it is a ``searxng`` directory
    in the tool's state directory (see ``state.state_dir``), which is beside the
    configured env file when there is one, so a container that mounts its config
    directory keeps the install across runs.
    """
    explicit = os.environ.get(HOME_VAR)
    if explicit:
        return Path(explicit).expanduser().resolve()
    from .state import state_dir

    return (state_dir() / "searxng").resolve()


def port() -> int:
    raw = os.environ.get(PORT_VAR, "").strip()
    if not raw:
        return DEFAULT_PORT
    try:
        value = int(raw)
    except ValueError as exc:
        raise SearxngError(f"{PORT_VAR}={raw!r} is not a port number") from exc
    if not 1 <= value <= 65535:
        raise SearxngError(f"{PORT_VAR}={value} is outside 1-65535")
    return value


def base_url(p: int | None = None) -> str:
    return f"http://127.0.0.1:{p if p is not None else port()}"


def _get(url: str, timeout_s: float) -> bytes:
    # Deliberately urllib and not the tool's own net layer: that layer honors the
    # configured proxy, and a loopback instance must never be reached through an exit
    # node. It also keeps this module importable with nothing but the standard library.
    request = urllib.request.Request(url, headers={"User-Agent": "websearch-searxng"})
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
    with opener.open(request, timeout=timeout_s) as response:
        return response.read()


def is_healthy(url: str, timeout_s: float = 2.0) -> bool:
    try:
        return _get(f"{url}/healthz", timeout_s).strip().upper().startswith(b"OK")
    except (urllib.error.URLError, OSError, ValueError):
        return False


def instance_info(url: str, timeout_s: float = 10.0) -> dict:
    """Version and engine counts from ``/config``; empty when it cannot be read."""
    try:
        config = json.loads(_get(f"{url}/config", timeout_s))
    except (urllib.error.URLError, OSError, ValueError):
        return {}
    engines = config.get("engines") or []
    return {
        "version": config.get("version"),
        "engines_active": sum(1 for e in engines if e.get("enabled")),
        "engines_available": len(engines),
    }


def _run(cmd: list[str], *, cwd: Path | None = None, what: str) -> None:
    try:
        done = subprocess.run(  # noqa: S603 - fixed argv, no shell
            cmd,
            cwd=str(cwd) if cwd else None,
            capture_output=True,
            text=True,
            env=_child_env(),
        )
    except FileNotFoundError as exc:
        raise SearxngError(f"{what} needs {cmd[0]!r}, which is not installed") from exc
    if done.returncode != 0:
        tail = (done.stderr or done.stdout or "").strip().splitlines()[-8:]
        raise SearxngError(f"{what} failed:\n" + "\n".join(tail))


def _child_env() -> dict[str, str]:
    """The environment for git and the package installer: the tool's egress, in their terms.

    ``git clone`` and ``uv pip install`` are downloads like any other, and they read the
    standard proxy variables rather than this tool's. Without them, installing SearXNG
    would be the one part of the bring-up that leaves from the machine's own address.
    """
    env = dict(os.environ)
    proxy = outgoing_proxy()  # raises when the lock is on and nothing is configured
    if not proxy:
        return env  # nothing configured here; whatever the shell already sets still applies
    for name in ("ALL_PROXY", "all_proxy", "HTTP_PROXY", "http_proxy", "HTTPS_PROXY"):
        env[name] = proxy
    env["https_proxy"] = proxy
    return env


def _clone(paths: Paths, ref: str | None) -> None:
    paths.home.mkdir(parents=True, exist_ok=True)
    cmd = ["git", "clone", "--depth", "1"]
    if ref:
        cmd += ["--branch", ref]
    cmd += [UPSTREAM, str(paths.src)]
    _run(cmd, what="cloning SearXNG")


def _make_venv(paths: Paths) -> None:
    # uv first: it is what the sandbox images ship, and an Alpine python3 has no
    # ensurepip, so the stdlib venv cannot bootstrap pip there at all.
    if shutil.which("uv"):
        _run(["uv", "venv", "--python", sys.executable, str(paths.venv)], what="creating the venv")
        return
    _run([sys.executable, "-m", "venv", str(paths.venv)], what="creating the venv")


def _install_deps(paths: Paths) -> None:
    requirements: list[str] = []
    for name in ("requirements.txt", "requirements-server.txt"):
        path = paths.src / name
        if path.exists():
            requirements += ["-r", str(path)]
    if not requirements:
        raise SearxngError(f"no requirements files in {paths.src}; the checkout looks wrong")
    if shutil.which("uv"):
        _run(
            ["uv", "pip", "install", "--python", str(paths.python), *requirements],
            what="installing SearXNG dependencies",
        )
        return
    _run(
        [str(paths.venv / "bin" / "pip"), "install", *requirements],
        what="installing SearXNG dependencies",
    )


def install(paths: Paths, *, ref: str | None = None, reinstall: bool = False) -> None:
    """Clone upstream and build the venv. A finished install is left alone."""
    if reinstall and paths.home.exists():
        shutil.rmtree(paths.home)
    if paths.src.exists() and not (paths.src / "searx").is_dir():
        raise SearxngError(f"{paths.src} exists but is not a SearXNG checkout; move it aside")
    if not paths.src.exists():
        _clone(paths, ref)
    if not paths.python.exists():
        _make_venv(paths)
    if not paths.granian.exists():
        _install_deps(paths)
    if not paths.granian.exists():
        raise SearxngError("the dependency install finished without producing granian")


def _existing_secret(text: str) -> str | None:
    """The secret_key already in a settings file, so a rewrite does not rotate it."""
    match = re.search(r'^\s*secret_key:\s*"([^"]+)"', text, re.MULTILINE)
    return match.group(1) if match else None


def _tor_socks() -> str | None:
    """The Tor SOCKS address to hand the onion engines, or None with the layer off."""
    from .proxy import ProxyConfigError, tor_enabled, tor_socks_url

    try:
        return tor_socks_url() if tor_enabled() else None
    except ProxyConfigError:
        # A malformed switch is the layer state's error to report; here it just means the
        # instance is configured without onion engines, which is the safe direction.
        return None


def outgoing_proxy() -> str | None:
    """Where this instance's own engine requests leave through, or None for direct.

    The instance is a second process, and everything it fetches leaves the machine: with
    the tool proxied and SearXNG not, every search still goes out from the real address
    while the fetches that follow do not. So it takes the same egress the CLI takes,
    Tor included when that layer is on.

    ``SEARXNG_OUTGOING_PROXY`` overrides it with a URL of your own, or an off word for
    direct egress; the same override the Docker stack takes. An unusable proxy raises
    rather than rendering settings without it: an instance that silently starts direct is
    the failure this exists to prevent.
    """
    from .proxy import OFF_WORDS, egress_proxy

    explicit = os.environ.get(OUTGOING_PROXY_VAR, "").strip()
    if explicit:
        return None if explicit.lower() in OFF_WORDS else explicit
    return egress_proxy()


def _is_ours(text: str) -> bool:
    """Whether this settings file is still the tool's to regenerate.

    The marker says so outright. A file written before the marker existed is adopted
    only when it is byte-identical to what that older version produced, which is the one
    case where rewriting cannot lose an edit: without this, every install that predates
    the tor layer would keep a settings file that can never gain the onion engines, and
    `websearch tor up` would quietly do nothing for SearXNG.
    """
    if MANAGED_MARKER in text:
        return True
    port = re.search(r"^\s*port:\s*(\d+)", text, re.MULTILINE)
    secret = _existing_secret(text)
    if not port or not secret:
        return False
    return text == LEGACY_SETTINGS_TEMPLATE.format(port=int(port.group(1)), secret=secret)


def _outgoing_block(proxy: str | None, tor_socks: str | None) -> str:
    """SearXNG's ``outgoing`` section: where its own engine requests leave from."""
    if not proxy and not tor_socks:
        return ""
    lines = ["outgoing:"]
    if tor_socks:
        # Off globally, on per onion engine. The global switch would make SearXNG verify
        # every engine's egress against check.torproject.org, which a VPN proxy fails.
        lines.append("  using_tor_proxy: false")
    if proxy:
        # extra_proxy_timeout buys the engines the round trip a proxied request costs;
        # without it a SOCKS exit turns ordinary engine latency into timeouts.
        lines += [
            "  proxies:",
            "    all://:",
            f"      - {proxy}",
            f"  extra_proxy_timeout: {EXTRA_PROXY_TIMEOUT_S}",
        ]
    return "\n".join(lines) + "\n"


def _render_settings(text: str, p: int, tor_socks: str | None, proxy: str | None) -> str:
    return SETTINGS_TEMPLATE.format(
        marker=MANAGED_MARKER,
        port=p,
        # Keeping the existing key matters: rotating it logs out every session and
        # invalidates the instance's own state for no reason.
        secret=_existing_secret(text) or secrets.token_hex(32),
        outgoing=_outgoing_block(proxy, tor_socks),
        engines=ONION_ENGINES_TEMPLATE.format(socks=tor_socks) if tor_socks else "",
    )


def settings_stale(paths: Paths, p: int, tor_socks: str | None, proxy: str | None) -> bool:
    """Whether a managed settings file no longer matches the settings it should hold."""
    try:
        text = paths.settings.read_text(encoding="utf-8")
    except OSError:
        return True
    if not _is_ours(text):
        return False  # the operator's file; never stale, never rewritten
    return text != _render_settings(text, p, tor_socks, proxy)


def write_settings(
    paths: Paths, p: int, *, tor_socks: str | None = None, proxy: str | None = None
) -> Path:
    """Write settings.yml, unless the file has stopped being ours.

    Regenerating is what lets a layer change actually reach the running instance: the
    onion engines need a Tor address, and the outgoing proxy changes whenever the egress
    does, neither of which a write-once file could ever gain. An operator who edits the
    file removes the managed marker (or the whole header) and this leaves it alone from
    then on.

    The file holds the proxy URL, credentials and all, which is why it is written 0600.
    """
    existing = ""
    if paths.settings.exists():
        existing = paths.settings.read_text(encoding="utf-8")
        if not _is_ours(existing):
            return paths.settings
    paths.settings.parent.mkdir(parents=True, exist_ok=True)
    paths.settings.write_text(_render_settings(existing, p, tor_socks, proxy), encoding="utf-8")
    paths.settings.chmod(0o600)
    return paths.settings


def running_pid(paths: Paths) -> int | None:
    """The pid from the pidfile when that process is still alive, else None."""
    try:
        pid = int(paths.pidfile.read_text().strip())
    except (OSError, ValueError):
        return None
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return None
    except PermissionError:
        return pid
    return pid


def start(paths: Paths, p: int) -> int:
    """Spawn granian in its own session, detached from the caller's process group."""
    env = dict(os.environ)
    env["SEARXNG_SETTINGS_PATH"] = str(paths.settings)
    env["PYTHONPATH"] = str(paths.src)
    env["GRANIAN_INTERFACE"] = "wsgi"
    env["GRANIAN_HOST"] = "127.0.0.1"
    env["GRANIAN_PORT"] = str(p)
    env["GRANIAN_WEBSOCKETS"] = "false"
    env["GRANIAN_PROCESS_NAME"] = "searxng"
    # The tool's own proxy settings and credentials belong to the client hop, not to
    # this server's environment: its egress is already in settings.yml, and a detached
    # process has no business holding the NordVPN credentials.
    leaked = ("WEBSEARCH_PROXY", "WEBSEARCH_VPN", "NORDVPN_USER", "NORDVPN_PASS", "NORDVPN_HOST")
    for name in leaked:
        env.pop(name, None)

    paths.log.parent.mkdir(parents=True, exist_ok=True)
    log = paths.log.open("ab")
    try:
        child = subprocess.Popen(  # noqa: S603 - fixed argv, no shell
            [str(paths.granian), "searx.webapp:app"],
            cwd=str(paths.src),
            env=env,
            stdin=subprocess.DEVNULL,
            stdout=log,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
    finally:
        log.close()
    paths.pidfile.write_text(f"{child.pid}\n", encoding="utf-8")
    return child.pid


def wait_healthy(url: str, timeout_s: int = HEALTH_TIMEOUT_S) -> bool:
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        if is_healthy(url):
            return True
        time.sleep(0.5)
    return False


def stop(paths: Paths, timeout_s: float = 10.0) -> bool:
    """Signal the whole session and wait for it to go. False when nothing was running."""
    pid = running_pid(paths)
    if pid is None:
        paths.pidfile.unlink(missing_ok=True)
        return False
    for sig in (signal.SIGTERM, signal.SIGKILL):
        try:
            os.killpg(os.getpgid(pid), sig)
        except (ProcessLookupError, PermissionError):
            break
        deadline = time.monotonic() + timeout_s
        while time.monotonic() < deadline:
            if running_pid(paths) is None:
                paths.pidfile.unlink(missing_ok=True)
                return True
            time.sleep(0.2)
    paths.pidfile.unlink(missing_ok=True)
    return True


def wire_env_file(url: str) -> Path | None:
    """Record the URL in the settings file the tool reads, so later commands pick it up.

    ``write_env_setting`` picks the file: ``WEBSEARCH_ENV_FILE`` when configured, else the
    user config file. None means nothing was written and the caller prints the export
    line instead.
    """
    return write_env_setting(SEARXNG_ENV, url)


_SETTINGS_PROXY_RE = re.compile(r"^\s*proxies:\s*\n\s*all://:\s*\n\s*-\s*(\S+)", re.MULTILINE)


def settings_egress(paths: Paths) -> str | None:
    """The proxy the settings file gives the instance, or None for direct egress.

    Read from the file rather than from the current environment on purpose: settings are
    read once at startup, so this is where the running process actually sends its engine
    requests, which is the only version of the answer worth reporting.
    """
    try:
        text = paths.settings.read_text(encoding="utf-8")
    except OSError:
        return None
    match = _SETTINGS_PROXY_RE.search(text)
    return match.group(1) if match else None


def status(paths: Paths, p: int) -> dict:
    url = base_url(p)
    pid = running_pid(paths)
    healthy = is_healthy(url)
    state = {
        "home": str(paths.home),
        "url": url,
        "installed": paths.granian.exists(),
        "pid": pid,
        "healthy": healthy,
        "egress": redact_url(settings_egress(paths)),
        "log": str(paths.log) if paths.log.exists() else None,
    }
    if healthy:
        state.update(instance_info(url))
    return state


# --- the contract face --------------------------------------------------------------


class SearxngRequest(BaseModel):
    """Mirrors contracts/searxng.schema.json#/$defs/SearxngRequest."""

    model_config = ConfigDict(extra="forbid")

    action: Literal["up", "status", "down"]
    reinstall: bool = False
    ref: str | None = None


class SearxngPayload(BaseModel):
    """Mirrors contracts/searxng.schema.json#/$defs/SearxngPayload."""

    model_config = ConfigDict(extra="forbid")

    action: Literal["up", "status", "down"]
    home: str
    url: str
    installed: bool
    pid: int | None = None
    healthy: bool
    egress: str | None = None
    wired: str | None = None
    version: str | None = None
    engines_active: int | None = Field(default=None, ge=0)
    engines_available: int | None = Field(default=None, ge=0)
    log: str | None = None


def _payload(action: str, paths: Paths, p: int, *, wired: Path | None) -> SearxngPayload:
    state = status(paths, p)
    return SearxngPayload(
        action=action,  # type: ignore[arg-type]
        home=state["home"],
        url=state["url"],
        installed=state["installed"],
        pid=state["pid"],
        healthy=state["healthy"],
        egress=state["egress"],
        wired=str(wired) if wired else None,
        version=state.get("version"),
        engines_active=state.get("engines_active"),
        engines_available=state.get("engines_available"),
        log=state["log"],
    )


def refresh_if_running() -> str | None:
    """Restart a running instance whose settings no longer match the egress. Returns its
    URL when it was restarted, else None.

    Settings are read once at startup, so an instance started before the exit changed
    keeps using the old one: the searches would still come from the previous city while
    everything else moved. Called by the commands that change the egress.
    """
    try:
        p = port()
    except SearxngError:
        return None
    paths = Paths(home_dir())
    url = base_url(p)
    if running_pid(paths) is None or not is_healthy(url):
        return None
    tor_socks = _tor_socks()
    proxy = outgoing_proxy()
    if not settings_stale(paths, p, tor_socks, proxy):
        return None
    write_settings(paths, p, tor_socks=tor_socks, proxy=proxy)
    stop(paths)
    start(paths, p)
    return url if wait_healthy(url) else None


def _error(code: str, message: str, *, retriable: bool) -> Envelope:
    return error_envelope(
        SEARXNG_CONTRACT_VERSION,
        code=code,
        message=message,
        retriable=retriable,
        layer="searxng",
        backend="searxng-local",
    )


def control(request: SearxngRequest) -> Envelope:
    """Run one lifecycle action and describe the resulting state.

    The single entry point behind both the ``searxng`` CLI command and the
    ``searxng_setup`` MCP tool, so the two faces cannot drift.
    """
    started = time.monotonic()
    try:
        p = port()
    except SearxngError as exc:
        return _error(errors.INVALID_REQUEST, str(exc), retriable=False)
    paths = Paths(home_dir())
    url = base_url(p)

    if request.action == "status":
        return _ok(_payload("status", paths, p, wired=None), started)

    if request.action == "down":
        stop(paths)
        return _ok(_payload("down", paths, p, wired=None), started)

    tor_socks = _tor_socks()
    try:
        proxy = outgoing_proxy()
    except ProxyConfigError as exc:
        return _error(errors.INVALID_REQUEST, str(exc), retriable=False)
    if is_healthy(url):
        # Never install over something that is already answering. It may still need a
        # restart: an instance started before the egress changed still uses the old one,
        # and settings are only read at startup.
        if settings_stale(paths, p, tor_socks, proxy) and running_pid(paths) is not None:
            write_settings(paths, p, tor_socks=tor_socks, proxy=proxy)
            stop(paths)
            start(paths, p)
            if not wait_healthy(url):
                return _error(
                    errors.UPSTREAM_ERROR,
                    f"SearXNG did not come back after a settings change; its log is at {paths.log}",
                    retriable=True,
                )
        return _ok(_payload("up", paths, p, wired=wire_env_file(url)), started)
    try:
        if request.reinstall or not paths.granian.exists():
            install(paths, ref=request.ref, reinstall=request.reinstall)
        write_settings(paths, p, tor_socks=tor_socks, proxy=proxy)
        start(paths, p)
    except SearxngError as exc:
        return _error(errors.DEPENDENCY_MISSING, str(exc), retriable=False)
    if not wait_healthy(url):
        stop(paths)
        return _error(
            errors.UPSTREAM_ERROR,
            f"SearXNG did not answer at {url} within {HEALTH_TIMEOUT_S}s; its log is at "
            f"{paths.log}",
            retriable=True,
        )
    return _ok(_payload("up", paths, p, wired=wire_env_file(url)), started)


def _ok(payload: SearxngPayload, started: float) -> Envelope:
    return ok_envelope(
        SEARXNG_CONTRACT_VERSION,
        payload.model_dump(mode="json"),
        layer="searxng",
        backend="searxng-local",
        elapsed_ms=round((time.monotonic() - started) * 1000, 3),
    )
